### ISSUE TITLE
ArgumentCountError

### ISSUE THREAD

**Issue by olimortimer** [ash-jc-allen/laravel-exchange-rates#121]
Hi,

Noticed you now allow different drivers, which is great, so I've dropped my fork and reinstalled this repo, however I'm receiving an 'ArgumentCountError' error when using it.

```
Too few arguments to function Illuminate\Support\Manager::__construct(), 0 passed in XXX on line Y and exactly 1 expected
```

It has been a long day, but I don't think I'm missing anything silly.

```
'driver' => 'exchange-rates-data-api',
'api_key' => env('EXCHANGE_RATES_API_KEY'),
```

```
EXCHANGE_RATES_API_KEY=<apikey>
```

**Comment by ash-jc-allen** [comment]
Hey @olimortimer,

Huge thanks for flagging this for me. It looks like I've forgotten to update the docs and upgrade guide to mention this part 🤦‍♂️

**Context**

Just for a bit of context (for yourself or anyone who might run into this issue too):

As of v6.0.0, the `AshAllenDesign\LaravelExchangeRates\Classes\ExchangeRate` class isn't directly responsible for handling the exchange rates anymore. Instead, it's a manager class that forwards the method call to the correct driver class that you want to use.

So from v6.0.0 onwards, this class should be resolved from the container rather than just using `new ExchangeRate()`. Instead, you should use something like this instead:

```php
use AshAllenDesign\LaravelExchangeRates\Classes\ExchangeRate;

$exchangeRate = app(ExchangeRate::class)->exchangeRate(...);
```

Alternatively, you could also use the facade like so:

```php
use AshAllenDesign\LaravelExchangeRates\Facades\ExchangeRate;

$exchangeRate = ExchangeRate::exchangeRate(...);
```

Sorry for any problems it might have caused for you! I'll get the docs updated today 😄

Does using one of the above approaches get your code running again?

**Comment by olimortimer** [comment]
Perfect, thank you.  The following did the trick;

```
use AshAllenDesign\LaravelExchangeRates\Facades\ExchangeRate;

$exchangeRate = ExchangeRate::exchangeRate('GBP', 'EUR');
```
